cursor_trail		0
copy_on_select		yes

cursor_shape		block

enable_audio_bell	no

cursor_beam_thickness	3

font_family		courier prime
bold_font		auto
italic_font		auto
bold_italic_font	auto

# modify_font		cell_width 100%
# modify_font		cell_height 0px
# modify_font		baseline -4

font_size		16

hide_window_decorations	no

map ctrl+equal		change_font_size all +1.0
map ctrl+minus		change_font_size all -1.0
map ctrl+0		change_font_size all 0
map ctrl+)		change_font_size all 0
map ctrl+f10		change_font_size all 38.0

shell_integration	no-cursor

confirm_os_window_close	0

window_border_width	0
window_margin_width	2

include			rose-pine.conf

background_opacity	0.85
background              #000000

linux_display_server	x11
