# # Monochrome theme
background            #000000
foreground            #FFFFFF
cursor                #FFFFFF

# black
color0                #000000
color8                #444444

# red
color1                #666666
color9                #AAAAAA

# green
color2                #666666
color10               #AAAAAA

# yellow
color3                #666666
color11               #AAAAAA

# blue
color4                #666666
color12               #AAAAAA

# magenta
color5                #666666
color13               #AAAAAA

# cyan
color6                #666666
color14               #AAAAAA

# white
color7                #BBBBBB
color15               #FFFFFF
