include = ~/.config/foot/rosepine

font=comic code:size=22,zen maru gothic:size=22

bold-text-in-bright=no
initial-window-size-chars=90x20
line-height=25.0

[cursor]
beam-thickness=2px
underline-thickness=3px

[colors-dark]
alpha=1
# background=000000
cursor=191724 ec5d2a

