exec-once = [workspace 1 silent] firefox
exec-once = [workspace 5 silent] steam-native

exec-once = ~/.config/hypr/scripts/setxkbmap.sh

exec-once = blueman-applet
exec-once = ckb-next
exec-once = mpd --no-daemon
exec-once = dunst
exec-once = fcitx5
exec-once = nm-applet
exec-once = ~/.config/hypr/scripts/background-autostart.sh

exec-once = udiskie --tray
exec-once = wl-paste --watch cliphist store --no-persist

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=hyprland
exec-once = dbus-update-activation-environment --systemd --all

exec-once = systemctl --user import-environment QT_QPA_PLATFORMTHEME
exec-once = systemctl --user start hyprpolkitagent

exec-once = dbus-update-activation-environment --all
exec-once = gnome-keyring-daemon --start --components=secrets,ssh
