input {
    kb_layout  = ca

    kb_options = # grp:alt_space_toggle

    follow_mouse = 1

    sensitivity = 0
    accel_profile = flat

    touchpad {
        natural_scroll = true
    }
}

gesture = 3, horizontal, workspace
gesture = 3, swipe, mod: $mainMod, resize

device {
    name=wacom-one-by-wacom-m-pen
    output=HDMI-A-1
    enabled = true
    # active_area_position = 10, 10
    # active_area_size = 90, 80
}

device {
    name=elan06fa:00-04f3:327e-touchpad
    enabled = true
}

cursor {
    hide_on_key_press = 1
    hide_on_tablet = 0
    inactive_timeout = 15
}

