windowrule = match:class mpv,              opacity 100

windowrule = match:float true, rounding 10

windowrule = match:title ^Incrustation vidéo$,          opacity 100
windowrule = match:title ^Picture-in-Picture$,          opacity 100
# windowrule = match:class negative:org.mitchellh.ghostty,         no_blur on

windowrule = match:title Minecraft.*,                   render_unfocused on
windowrule = match:class overwatch.exe,                 render_unfocused on
windowrule = match:class steam_app_2357570,             render_unfocused on
windowrule = match:class forzahorizon.exe,              render_unfocused on

windowrule = match:class steam_app_1551360,             float on, persistent_size on
windowrule = match:class xdg-desktop-portal-gtk,        float on, persistent_size on

windowrule = match:title Minecraft.*,                   immediate yes
windowrule = match:class overwatch.exe,                 immediate yes
windowrule = match:class steam_app_2357570,             immediate yes
windowrule = match:class forzahorizon.exe,              immediate yes

# windowrule = match:class org.pulseaudio.pavucontrol,    float on
# windowrule = match:class org.pulseaudio.pavucontrol,    size 900 300
# windowrule = match:class org.pulseaudio.pavucontrol,    center on

# windowrule = match:class thunar,                        float on
# windowrule = match:class thunar,                        size 900 300
# windowrule = match:class thunar,                        center on

windowrule = match:title Save.*,                        float on
windowrule = match:title Save.*,                        size 1000 700
windowrule = match:title Save.*,                        center on

windowrule = match:pin on, border_size 5, border_color rgb(FF0000) rgb(880808)

windowrule = match:class .*,                            suppress_event maximize
windowrule = match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false, no_focus true

