workspace = 1,      monitor:HDMI-A-1,   default:true
workspace = 2,      monitor:HDMI-A-1
workspace = 3,      monitor:HDMI-A-1
workspace = 4,      monitor:HDMI-A-1
workspace = 5,      monitor:HDMI-A-1
workspace = 6,      monitor:HDMI-A-1
workspace = 7,      monitor:HDMI-A-1
workspace = 8,      monitor:HDMI-A-1
workspace = 9,      monitor:HDMI-A-1
workspace = 10,     monitor:eDP-1,      default:true

workspace = s[1], gapsout:50, gapsin:0, bordersize:5
workspace = 4, gapsout:25, gapsin:0, bordersize:5
workspace = 3, layout:scrolling
workspace = 10, layout:scrolling

# windowrule = match:class org.pwmt.zathura,              workspace 3

windowrule = match:title Minecraft.*,                   workspace 4
windowrule = match:class cs2,                           workspace 4
windowrule = match:class worldofwarships64.exe,         workspace 4
windowrule = match:class forzahorizon5.exe,             workspace 4
windowrule = match:class overwatch.exe,                 workspace 4
windowrule = match:class discovery.exe,                 workspace 4
windowrule = match:class ADanceOfFireAndIce,            workspace 4
windowrule = match:class steam_app.*,                   workspace 4

windowrule = match:class steam,                         workspace 5
windowrule = match:class vesktop,                       workspace 8
windowrule = match:class Element,                       workspace 9

windowrule = match:class org.mozilla.Thunderbird,       workspace 7

windowrule = match:title ^Incrustation vidéo$,          workspace 10 silent
windowrule = match:title ^Picture-in-Picture$,          workspace 10 silent

windowrule = match:class alacritty.scratch,             workspace special:specialwork
