[general]
working_directory = "~"
import = [
  "~/.config/alacritty/rosé-pine.toml",
  # "~/.config/alacritty/nvim-generated.toml"
]

[window]
opacity = 1
dynamic_padding = true


[colors.cursor]
cursor = "#EC5D2A"

[font]
normal = { family = "comic code" }
size = 20

[keyboard]
bindings = [
    { key = ")", mods = "Control", mode = "AppCursor", action = "ResetFontSize" },
]
