[general]
import = [
  # "~/.config/alacritty/rosé-pine.toml",
]

[window]
opacity = 0.96
dynamic_padding = true


[colors.cursor]
cursor = "#EC5D2A"

[font]
# normal = { family = "comic code" }
normal = { family = "courier prime" }
size = 20

[keyboard]
bindings = [
    { key = ")", mods = "Control", mode = "AppCursor", action = "ResetFontSize" },
]
