#!/usr/bin/env bash

# ~/.config/polybar/launch.sh &
~/.config/i3/xrandr.sh &

# i3bar &
# fcitx5 &
blueman-applet &
ckb-next-daemon &
dunst &
nm-applet &
udiskie --tray &
xss-lock -- i3lock -c 191724 &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
gnome-keyring-daemon --start --components=secrets &
systemctl --user enable --now opentabletdriver.service &
systemctl enable --now auto-cpufreq.service &
nitrogen --restore &
fastcompmgr -m 1 -C -i 0.86 -e 1 -D 0 &
setxkbmap ca &
setxkbmap -layout ca &
xset r rate 250 50 &
xset s 540 600 &
xset dpms 600 600 600 &
unclutter --timeout 15 &
gammastep -m randr -l 46.3:-72.5 &
greenclip daemon &
