---@diagnostic disable: undefined-global

-- Surtr: ember monotone generated by matugen
-- source:
-- 	https://codeberg.org/rozes/wallpapers/src/branch/main/wall/surtr-sitting-lava.jpg

local colors = {
  white = "#fdfbe4",
  darker_black = "#0C0404",
  black = "#000000",
  black2 = "#170908",
  one_bg = "#1D0C0A",
  one_bg2 = "#27110D",
  one_bg3 = "#361A14",
  grey = "#4A2820",
  grey_fg = "#5C3A2E",
  grey_fg2 = "#7A4E3E",
  light_grey = "#94614E",

  red = "#DD5645",
  baby_pink = "#DD5645",
  pink = "#B84336",
  line = "#1D0C0A",

  green = "#DD5645",
  vibrant_green = "#E86A55",
  nord_blue = "#DD5645",
  blue = "#DD5645",
  yellow = "#EF6B54",
  sun = "#F0785E",
  purple = "#C8503F",
  dark_purple = "#8A4638",
  teal = "#DD5645",
  orange = "#DD5645",
  cyan = "#DD5645",

  statusline_bg = "#1D0C0A",
  lightbg = "#27110D",
  pmenu_bg = "#361A14",
  folder_bg = "#DD5645",
}

local colorDefinitions = {
  defaults = {
    Normal = { fg = colors.red, bg = colors.black },
    NormalNC = { fg = colors.red, bg = colors.black },
    NormalFloat = { fg = colors.red, bg = colors.one_bg2 },
    FloatBorder = { fg = colors.grey, bg = colors.one_bg2 },
    FloatTitle = { fg = colors.red, bg = colors.one_bg2, bold = true },

    CursorLine = { bg = colors.one_bg },
    ColorColumn = { bg = colors.one_bg },
    LineNr = { fg = colors.grey, bg = colors.black },
    CursorLineNr = { fg = colors.yellow, bg = colors.one_bg, bold = true },
    SignColumn = { fg = colors.grey, bg = colors.black },

    Visual = { fg = colors.black, bg = colors.baby_pink },
    VisualNOS = { fg = colors.black, bg = colors.baby_pink },
    Search = { fg = colors.black, bg = colors.yellow },
    IncSearch = { fg = colors.black, bg = colors.sun, bold = true },
    CurSearch = { fg = colors.black, bg = colors.sun, bold = true },

    Pmenu = { fg = colors.red, bg = colors.one_bg2 },
    PmenuSel = { fg = colors.black, bg = colors.baby_pink, bold = true },
    PmenuThumb = { bg = colors.sun },
    PmenuSbar = { bg = colors.one_bg2 },
    PmenuMatch = { fg = colors.red, bold = true },
    PmenuMatchSel = { fg = colors.black, bold = true },

    StatusLine = { fg = colors.sun, bg = colors.one_bg },
    StatusLineNC = { fg = colors.grey, bg = colors.black },

    Comment = { fg = colors.grey, italic = true },
    String = { fg = colors.sun },
    Number = { fg = colors.white },
    Boolean = { fg = colors.red, bold = true },
    Function = { fg = colors.red, bold = true },
    Keyword = { fg = colors.red, bold = true },
    Statement = { fg = colors.yellow, bold = true },
    Type = { fg = colors.red },
    Constant = { fg = colors.sun },
    Identifier = { fg = colors.red },
    Operator = { fg = colors.red },
    Delimiter = { fg = colors.red },
    Special = { fg = colors.red },
    Todo = { fg = colors.black, bg = colors.yellow, bold = true },
    Error = { fg = colors.white, bg = colors.red, bold = true },
  },

  treesitter = {
    ["@comment"] = { fg = colors.grey, italic = true },
    ["@string"] = { fg = colors.sun },
    ["@string.escape"] = { fg = colors.yellow },
    ["@number"] = { fg = colors.white },
    ["@number.float"] = { fg = colors.white },
    ["@boolean"] = { fg = colors.red, bold = true },

    ["@function"] = { fg = colors.red, bold = true },
    ["@function.call"] = { fg = colors.red },
    ["@function.builtin"] = { fg = colors.red },
    ["@function.method"] = { fg = colors.red },
    ["@function.method.call"] = { fg = colors.red },

    ["@keyword"] = { fg = colors.red, bold = true },
    ["@keyword.function"] = { fg = colors.red, bold = true },
    ["@keyword.return"] = { fg = colors.red, bold = true },
    ["@keyword.operator"] = { fg = colors.red, bold = true },
    ["@operator"] = { fg = colors.red },

    ["@type"] = { fg = colors.red },
    ["@type.builtin"] = { fg = colors.red, bold = true },

    ["@variable"] = { fg = colors.sun },
    ["@variable.parameter"] = { fg = colors.sun },
    ["@variable.builtin"] = { fg = colors.sun },
    ["@constant"] = { fg = colors.sun },
    ["@constant.builtin"] = { fg = colors.sun, bold = true },

    ["@property"] = { fg = colors.red },
    ["@field"] = { fg = colors.red },
    ["@punctuation.delimiter"] = { fg = colors.red },
    ["@punctuation.bracket"] = { fg = colors.red },

    ["@markup.heading"] = { fg = colors.yellow, bold = true },
    ["@markup.link"] = { fg = colors.purple, underline = true },
    ["@markup.link.url"] = { fg = colors.purple, underline = true },

    ["@constant.macro"] = { fg = colors.yellow, bold = true },
    ["@function.macro"] = { fg = colors.red, bold = true },
    ["@keyword.directive"] = { fg = colors.sun, bold = true },
    ["@keyword.directive.define"] = { fg = colors.yellow, bold = true },
  },

  nvimtree = {
    NvimTreeNormal = { fg = colors.red, bg = colors.black },
    NvimTreeFolderName = { fg = colors.sun },
    NvimTreeOpenedFolderName = { fg = colors.yellow, bold = true },
    NvimTreeRootFolder = { fg = colors.red, bold = true },
    NvimTreeGitDirty = { fg = colors.yellow },
    NvimTreeGitNew = { fg = colors.red },
    NvimTreeGitDeleted = { fg = colors.red },
  },

  telescope = {
    TelescopeNormal = { fg = colors.red, bg = colors.one_bg2 },
    TelescopeBorder = { fg = colors.grey, bg = colors.one_bg2 },
    TelescopePromptNormal = { fg = colors.red, bg = colors.one_bg },
    TelescopePromptBorder = { fg = colors.grey, bg = colors.one_bg },
    TelescopeSelection = { fg = colors.black, bg = colors.baby_pink, bold = true },
    TelescopeMatching = { fg = colors.yellow, bold = true },
  },

  extra = {
    Cursor = { fg = colors.black, bg = colors.baby_pink },
    lCursor = { fg = colors.black, bg = colors.baby_pink },
    CursorIM = { fg = colors.black, bg = colors.baby_pink },
    TermCursor = { fg = colors.black, bg = colors.baby_pink },
    TermCursorNC = { fg = colors.black, bg = colors.grey },

    VertSplit = { fg = colors.grey, bg = colors.black },
    WinSeparator = { fg = colors.grey, bg = colors.black },
    WinBar = { fg = colors.red, bg = colors.black, bold = true },
    WinBarNC = { fg = colors.grey, bg = colors.black },
    TabLine = { fg = colors.grey, bg = colors.one_bg },
    TabLineFill = { bg = colors.one_bg },
    TabLineSel = { fg = colors.red, bg = colors.black, bold = true },

    MatchParen = { fg = colors.yellow, bold = true, underline = true },
    Title = { fg = colors.sun, bold = true },
    Directory = { fg = colors.red, bold = true },
    Folded = { fg = colors.grey, bg = colors.one_bg, italic = true },
    FoldColumn = { fg = colors.grey, bg = colors.black },
    NonText = { fg = colors.grey },
    SpecialKey = { fg = colors.grey },
    Whitespace = { fg = colors.one_bg3 },
    EndOfBuffer = { fg = colors.black },
    Conceal = { fg = colors.grey },

    DiffAdd = { fg = colors.red, bg = colors.one_bg },
    DiffChange = { bg = colors.one_bg },
    DiffDelete = { fg = colors.grey, bg = colors.one_bg2 },
    DiffText = { fg = colors.red, bg = colors.one_bg3, bold = true },

    DiagnosticError = { fg = colors.yellow, bold = true },
    DiagnosticWarn = { fg = colors.yellow },
    DiagnosticInfo = { fg = colors.grey },
    DiagnosticHint = { fg = colors.grey, italic = true },
    DiagnosticOk = { fg = colors.grey },
    DiagnosticUnderlineError = { undercurl = true, sp = colors.yellow },
    DiagnosticUnderlineWarn = { undercurl = true, sp = colors.yellow },
    DiagnosticUnderlineInfo = { undercurl = true, sp = colors.grey },
    DiagnosticUnderlineHint = { undercurl = true, sp = colors.grey },
    DiagnosticSignError = { fg = colors.yellow, bold = true },
    DiagnosticSignWarn = { fg = colors.yellow },
    DiagnosticSignInfo = { fg = colors.grey },
    DiagnosticSignHint = { fg = colors.grey },
    DiagnosticFloatingError = { fg = colors.yellow, bold = true },
    DiagnosticFloatingWarn = { fg = colors.yellow },
    DiagnosticFloatingInfo = { fg = colors.grey },
    DiagnosticFloatingHint = { fg = colors.grey, italic = true },
    DiagnosticVirtualTextError = { fg = colors.yellow, bold = true },
    DiagnosticVirtualTextWarn = { fg = colors.yellow },
    DiagnosticVirtualTextInfo = { fg = colors.grey },
    DiagnosticVirtualTextHint = { fg = colors.grey, italic = true },

    LspReferenceText = { bg = colors.one_bg },
    LspReferenceRead = { bg = colors.one_bg },
    LspReferenceWrite = { bg = colors.one_bg, bold = true },
    LspInlayHint = { fg = colors.grey, bg = colors.one_bg, italic = true },
    LspCodeLens = { fg = colors.grey, italic = true },
    LspSignatureActiveParameter = { bg = colors.one_bg2, bold = true },

    GitSignsAdd = { fg = colors.red },
    GitSignsChange = { fg = colors.grey },
    GitSignsDelete = { fg = colors.yellow },
    GitSignsAddPreview = { fg = colors.red, bg = colors.one_bg },
    GitSignsDeletePreview = { fg = colors.yellow, bg = colors.one_bg },
    GitSignsAddInline = { bg = colors.one_bg },
    GitSignsChangeInline = { bg = colors.one_bg },
    GitSignsDeleteInline = { bg = colors.one_bg2 },
    GitSignsCurrentLineBlame = { fg = colors.grey, italic = true },
  },
}

vim.cmd("highlight clear")

if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end

vim.g.colors_name = "surtr"

for group, opts in pairs(colorDefinitions.defaults) do
  vim.api.nvim_set_hl(0, group, opts)
end

for group, opts in pairs(colorDefinitions.treesitter) do
  vim.api.nvim_set_hl(0, group, opts)
end

for group, opts in pairs(colorDefinitions.nvimtree) do
  vim.api.nvim_set_hl(0, group, opts)
end

for group, opts in pairs(colorDefinitions.telescope) do
  vim.api.nvim_set_hl(0, group, opts)
end

for group, opts in pairs(colorDefinitions.extra) do
  vim.api.nvim_set_hl(0, group, opts)
end
