#!/usr/bin/env bash

drive_path="$1"
backup_path="$drive_path/backup"
date_str="$(date +%F_%H-%M-%S)"

mkdir -p "$backup_path"

tar -czvf "$backup_path/$date_str.tar.gz" \
  -C "$HOME" \
  .config \
  art \
  book \
  cours \
  Documents \
  dotfiles \
  maple2022 \
  Music \
  notes \
  repos \
  wallpapers \
  .aliases.sh \
  .email \
  .ghci \
  .gitconfig \
  .tmux.conf \
  .tmux.vague-theme.conf \
  .vimrc \
  .zshrc
