#!/usr/bin/env bash

sudo cp \
  /home/hiver/Desktop/dev/root/usr/share/xkeyboard-config-2/symbols/ca \
  /usr/share/xkeyboard-config-2/symbols/ca

sudo cp \
  /home/hiver/Desktop/dev/root/usr/share/xkeyboard-config-2/symbols/fr \
  /usr/share/xkeyboard-config-2/symbols/fr

sudo cp \
  /home/hiver/Desktop/dev/root/usr/share/xkeyboard-config-2/symbols/us \
  /usr/share/xkeyboard-config-2/symbols/us

sudo cp \
  /home/hiver/Desktop/dev/root/usr/share/xkeyboard-config-2/symbols/ru \
  /usr/share/xkeyboard-config-2/symbols/ru

sudo cp \
  /home/hiver/Desktop/dev/root/usr/share/xkeyboard-config-2/symbols/de \
  /usr/share/xkeyboard-config-2/symbols/de

sudo cp \
  /home/hiver/Desktop/dev/root/usr/share/xkeyboard-config-2/symbols/latin \
  /usr/share/xkeyboard-config-2/symbols/latin
