#!/usr/bin/env bash

tmp="$(mktemp)"

DIRECTORIES=(
  "$HOME/Pictures"
  "$HOME/Downloads"
  "$HOME/notes"
  "$HOME/Documents"
)

alacritty -e bash -lc \
  "fd -e jpg -e jpeg -e png -e webp -e gif -e bmp -e tif -e tiff -e heic . ${DIRECTORIES[*]} | fzf -m >\"$tmp\""

if [ ! -s "$tmp" ]; then
  rm -f -- "$tmp"
  exit 1
fi

mapfile -t selected <"$tmp"
rm -f -- "$tmp"

((${#selected[@]} == 0)) && exit 1

nohup imv "${selected[@]}" >/dev/null 2>&1 &
