#!/usr/bin/env bash

PKG_LIST="$HOME/.pkg-list"

case "$1" in
    i|install)
        paru -Syu --needed $(<"$PKG_LIST")
        ;;
    *)
        echo "Fetching pkgs"
        paru -Qqe > "$PKG_LIST"
	echo "$(cat $PKG_LIST| wc -l) pkgs fetched"
        ;;
esac
