#!/usr/bin/env bash

PKG_LIST="$HOME/.pkg-list"

currentCount=$(wc -l <"$PKG_LIST" 2>/dev/null || echo 0)

case "$1" in
i | install)
	paru -Syu --needed $(<"$PKG_LIST")
	;;
*)
	echo "Fetching pkgs"
	paru -Qqe >"$PKG_LIST"
	newCount=$(cat $PKG_LIST | wc -l)

	diff=$((newCount - currentCount))
	if ((diff > 0)); then
		echo "+$diff pkgs diff"
	else
		echo "$diff pkgs diff"
	fi

	echo "$newCount pkgs currently fetched"
	;;
esac
