#!/usr/bin/env bash

extraFlags="$@"

_local="$HOME"
_extern="/run/media/fuyu147/C87B-D012/shared-data"

dirs=(
  "art"
  "cours"
  "math"
  "notes"
)

for d in "${dirs[@]}"; do
  rsync -av --delete "$_extern/$d/" "$_local/$d/"
done
