#!/usr/bin/env bash

CATEGORIES="CODING
TRAVAIL
WASTE
STOP
"

if [[ -n "$1" ]]; then
  if [[ "$1" == "STOP" ]]; then
    timew stop >/dev/null 2>&1
    tmux set -g status-right "%H:%M"
  else
    timew start "$1" >/dev/null 2>&1
    tmux set -g status-right "$1 #(timew | awk '/^ *Total/ {print \$NF}') %H:%M"
  fi
else
  choice=$(echo "$CATEGORIES" | rofi -dmenu -p "Catégories" -i -no-fixed-num-lines -lines 20)

  if [[ "$choice" == "STOP" ]]; then
    timew stop >/dev/null 2>&1
    tmux set -g status-right "%H:%M"
  else
    timew start "$choice" >/dev/null 2>&1
    tmux set -g status-right "$choice #(timew | awk '/^ *Total/ {print \$NF}') %H:%M"
  fi
fi
