#!/usr/bin/env bash

# # To create the sink and stuff
#
# pactl load-module module-null-sink sink_name=tts_sink
#
# pactl load-module module-remap-source \
#     master=tts_sink.monitor \
#     source_name=tts_mic \
#     source_properties=device.description=TTS-Mic

set -x

tmpFile="/home/fuyu147/notes/tts-input.72.txt"
tmpOut=$(mktemp --suffix=.mp3)

trap 'rm -f "$tmpOut"' EXIT

/usr/bin/neovide --no-fork \
  "$tmpFile" \
  --wayland_app_id tts-neovide

text="$(
  grep -vE '^[[:space:]]*;;' "$tmpFile" |
  sed '/^[[:space:]]*$/d'
)"

/home/fuyu147/art/python-venv-thing/venv/bin/gtts-cli \
  -l fr \
  "$text" \
  -o "$tmpOut"

/usr/bin/mpv                               "$tmpOut" &
/usr/bin/mpv --audio-device=pulse/tts_sink "$tmpOut"
