#!/usr/bin/env bash

pids=()

cleanup() {
  for pid in "${pids[@]}"; do
    kill "$pid" 2>/dev/null
  done
  wait
  exit 130
}

trap cleanup INT

watch_file() {
  local file="$1"
  [[ -f "$file" ]] || return

  typst watch "$file" &
  pids+=($!)
}

# Start watchers for existing args
for file in "$@"; do
  watch_file "$file"
done

# Watch current directory for new .typ files
inotifywait -m -e create --format '%f' . | while read -r file; do
  [[ "$file" == *.typ ]] && watch_file "$file"
done
