#!/usr/bin/env bash

set -euo pipefail

SRC_DIRS=(
  "$HOME/repos/Synapse/"
  "$HOME/repos/hyprland/"
  "$HOME/repos/github-page/"
  "$HOME/art/linc/"
  "$HOME/notes"
  "$HOME/dotfiles"
)

DEST_DIR="/srv/git"

mkdir -p "$DEST_DIR" >/dev/null 2>&1
sudo rm -rf "$DEST_DIR"/* >/dev/null 2>&1

for SRC in "${SRC_DIRS[@]}"; do
  prefix="$(basename "$SRC")"

  # Case: SRC itself is a git repo
  # if [ -d "$SRC/.git" ]; then
  dest_repo="$DEST_DIR/${prefix}.git"
  git clone --bare "$SRC" "$dest_repo" >/dev/null 2>&1
  continue
  # fi
  #
  # # Case: SRC contains multiple repos
  # for repo in "$SRC"/*; do
  #   [ -d "$repo" ] || continue
  #   [ -d "$repo/.git" ] || continue
  #
  #   name="$(basename "$repo")"
  #   dest_repo="$DEST_DIR/${prefix}-${name}.git"
  #
  #   [ -d "$dest_repo" ] && continue
  #
  #   git clone --bare "$repo" "$dest_repo" >/dev/null 2>&1
  # done
done
