permit nopass :wheel
permit nopass yourusername as root cmd /sbin/reboot
permit nopass yourusername as root cmd /sbin/poweroff
permit nopass yourusername as root cmd /sbin/halt
permit nopass yourusername as root cmd /sbin/shutdown

