general {
    hide_cursor = true
}

background {
    monitor =
    path = $HOME/.current.wall
    blur_size = 8
    brightness = 0.2
    blur_passes = 2
}

input-field {
    placeholder_text =
    size = 435, 84
    rounding = 5
    outline_thickness = 3
    font_color = rgb(255, 255, 255)
    inner_color = rgba(0, 0, 0, 0)
    outer_color = rgb(0, 0, 0, 0)
    dots_size = 0.38
    fail_text = $FAIL ($ATTEMPTS)
    fail_color = rgba(229, 133, 133, 1)
    check_color = rgba(124, 190, 140, 1)
    capslock_color = rgba(142, 138, 111, 1)
    numlock_color = rgba(142, 138, 111, 1)
    fade_on_empty = false
    fade_timeout = 5500
    font_family = Courier Prime Code
    halign = center
    valign = center
    position = 0, -200
}

label {
    monitor =
    text = Locked
    font_size = 40
    font_family = Courier Prime Code
    halign = center
    valign = center
    position = 0, -135
}

# label {
#     monitor =
#     text = $TIME
#     font_size = 40
#     font_family = Courier Prime Code
#     halign = left
#     valign = bottom
#     position = 50, 100
# }

# label {
#     monitor =
#     text = cmd[update:1000] echo "$(uptime -p)"
#     font_size = 40
#     font_family = Courier Prime Code
#     halign = left
#     valign = bottom
#     position = 50, 50
# }


# image {
#     monitor =
#     path = ~/Documents/shinano-tiny-sleeping.jpg
#     size = 250
#     halign = center
#     valign = center
#     position = 0, 50
}
