source = ~/.config/hypr/confs/monitors.conf
source = ~/.config/hypr/confs/env.conf
source = ~/.config/hypr/confs/autostart.conf
source = ~/.config/hypr/confs/input.conf
source = ~/.config/hypr/confs/look-feel.conf
source = ~/.config/hypr/confs/binds-var.conf
source = ~/.config/hypr/confs/windowrules.conf
source = ~/.config/hypr/confs/workspaces.conf
