#!/usr/bin/env bash


pipewire &
wireplumber &
pipewire-pulse &
mpd --no-daemon &

blueman-applet &
ckb-next-daemon &
dunst &
fcitx5 &
nm-applet &
awww-daemon &
udiskie --tray &
wl-paste --watch cliphist store --no-persist &

dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway &
dbus-update-activation-environment --systemd --all &

dbus-update-activation-environment --all &
# gnome-keyring-daemon --start --components=secrets &

wlsunset -S 9:00 -s 21:00 &

# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

swayidle -w \
  timeout 1800 'hyprlock' \
  timeout 3600 'swaymsg "output * dpms off"' \
  resume 'swaymsg "output * dpms on"' &

./arrstack.sh &



