set -g status-left "#S > "
set -g status-right "%H:%M"
set -g status-style "fg=#cdcdcd,bg=#141415"
set -g window-status-separator " "
set -g window-status-format "#[fg=#cdcdcd] #I:#W #[default]"
set -g window-status-current-format "#{?client_prefix,#[fg=#7e98e8]¬,#[fg=#606079]}#[fg=#6e94b2, bg=#252530] #I:#W #[default]"
