set -g message-style "fg=black,bg=cyan"
# set -g status-left "#[fg=white, bg=black]#S#[default]"
set -g status-left ""
set -g status-right "#[fg=white]#S#[default] #[fg=black,bg=cyan]%H:%M:%S"
set -g status-style "fg=white"
set -g window-status-separator ""
set -g window-status-format "#[fg=white]#I"
set -g window-status-current-format "#[fg=black,bg=brightwhite]#I"
