set -g message-style "fg=black,bg=cyan"
set -g status-left "#[fg=white,bg=black] #S #[default]  >  "
set -g status-right "#(git rev-parse --abbrev-ref HEAD 2>/dev/null) #[fg=white,bg=black] %A %d %B #[fg=black,bg=cyan] %H:%M:%S "
set -g status-style "fg=white"
set -g window-status-separator " "
set -g window-status-format "#[fg=white] #I #W "
set -g window-status-current-format "#[fg=black,bg=brightwhite] #I #W "
